#!/bin/tcsh 

# rootRobot is to be used after cooking to make 
# root files out of the nt10 files
source /group/clas/builds/environment.csh

set files = `ls /volatile/clas/clas12/dmriser/analysis/ef1_analysis/rec_out/nt10/clas_*`

foreach file ($files)
    echo "working on $file.."
    h2root $file 
end
