#!/bin/tcsh -f



setenv CLAS_CALDB_RUNINDEX calib_user.RunIndexe1f

source /group/clas/builds/environment.csh

set jnumber  = $1
set gpp      = 1.3819
set logPath  = "/volatile/clas/clas12/dmriser/analysis/mcdata/logs"
set mainPath = "/u/home/dmriser/mydoc/cooking_supplies"

alias gpp_2008  $mainPath/mc_tools/gpp_2008 
alias user_ana  /volatile/clas/clas12/dmriser/analysis/ef1_analysis/temp/kjuser_ana
alias nt22maker /volatile/clas/clas12/dmriser/analysis/ef1_analysis/temp/NEWnt22maker 

echo " > preparing to start jobs <" > $logPath/$jnumber.log
echo " ==========================="

ls -lh 

echo "> using gsim exe `which gsim_bat`"  >> $logPath/$jnumber.log

gsim_bat -ffread ffread.in -mcin gen.bos -trig 20000 -kine 1 -bosout GSIMout.bos
echo "> gsim done!"  >> $logPath/$jnumber.log
echo " ==========================="
ls -lh

gpp_2008 -P0x1b -a$gpp -b$gpp -c$gpp -f0.75 -Y -R37662 -oGPPout.bos GSIMout.bos
echo "> gpp done!" >> $logPath/$jnumber.log
echo " ==========================="
ls -lh 

mv GPPout.bos Input 

user_ana -t recsis_e1f_MC.tcl >& /dev/null
echo "> user_ana done!">> $logPath/$jnumber.log
echo " ==========================="
ls -lh 

nt22maker --mc 2
echo " > nt22maker done!">> $logPath/$jnumber.log
echo " ==========================="
ls -lh 

# to get h2root 
source /group/clas12/environment.csh 

h2root dstfile.hbook out.root
echo "> h2root done!">> $logPath/$jnumber.log
echo " ==========================="
ls -lh 

echo "> job finished. ">> $logPath/$jnumber.log 

mv Input GPPout.bos 
